//ALERTS:
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//AUTH
export const USER_LOADED = "USER_LOADED";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const REGISTER_ERROR = "REGISTER_ERROR";

//CALENDAR
export const CALENDAR_LOADED = "CALENDAR_LOADED";
export const CALENDAR_LOADED_ERROR = "CALENDAR_LOADED_ERROR";
export const SET_DATE = "SET_DATE";
export const LOAD_MONTH_DATES = "LOAD_MONTH_DATES";
export const EVENTS_LOADED = "EVENTS_LOADED";
export const EVENT_WAS_UPDATED = "EVENT_WAS_UPDATED";

//CALENDAR EVENT
export const CREATE_EVENT = "CREATE_EVENT";
export const EVENT_CREATED = "EVENT_CREATED";
export const CREATE_EVENT_ERROR = "CREATE_EVENT_ERROR";
export const EVENT_ADDED = "EVENT_ADDED";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const EVENT_UPDATED = "EVENT_UPDATED";
export const UPDATE_EVENT_ERROR = "UPDATE_EVENT_ERROR";
export const SET_CURRENT_EVENT = "SET_CURRENT_EVENT";
export const UNSET_CURRENT_EVENT = "UNSET_CURRENT_EVENT";
