//ALERTS:
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//AUTH
export const USER_LOADED = "USER_LOADED";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const REGISTER_ERROR = "REGISTER_ERROR";

//CALENDAR
export const CALENDAR_LOADED = "CALENDAR_LOADED";
export const CALENDAR_LOADED_ERROR = "CALENDAR_LOADED_ERROR";
export const SET_DATE = "SET_DATE";
